var pilihIdExamination;
var checked;
var role;
var id_user;
var username;
var name;
var doctor_name;
var doctor_username;
var id_penerima;
var id_doctor;
var id_pasien;
var tanggallihatgrafik;
var jamlihatgrafik;
var id_data_diagnosa;
String foto_profil;
DateTime tanggal_lahir;
String phone;
String alamat;
String eemail;
String foto_profil_dok;
DateTime tanggal_lahir_dok;
String phone_dok;
String alamat_dok;
String eemail_dok;
String name_dok;
//String link = "http://34.126.80.36/dermits/";
//String link = "http://192.168.1.68/haloecg/";
String link = "http://haloecg.site/haloecgk/";
